name: Metrics

on:
  schedule:
    - cron: "17 0 */5 * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Generate achievements
        uses: lowlighter/metrics@v3.33
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          plugin_achievements_secrets: true
          config_timezone: America/Sao_Paulo
