name: Metrics

on:
  schedule:
    - cron: "17 0 */5 * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Generate achievements
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_rank_threshold: D
          plugin_achievements_display: compact
          plugin_achievements_limit: 0
          plugin_achievements_secrets: true
          random: ${{ github.run_id }}
          base: content
          config_timezone: America/Sao_Paulo
