name: Achievements Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1"

jobs:
  achievements:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Detailed achievements
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          config_timezone: America/Sao_Paulo
