name: Metrics

on:
  schedule:
    - cron: "17 0 */5 * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Generate achievements
        uses: lowlighter/metrics@v3.14.0  # Versão fixa para evitar bugs
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.GITHUB_TOKEN }}  # Use o token padrão
          plugin_achievements: yes
          plugin_achievements_rank_threshold: D  # Rank mais baixo = mais conquistas
          plugin_achievements_display: compact
          plugin_achievements_limit: 0          # Mostrar todas as conquistas
          plugin_achievements_secrets: true     # Incluir conquistas secretas
          random: ${{ github.run_id }}          # Força recálculo a cada execução
          base: content                         # Mantém conteúdo básico
          config_timezone: America/Sao_Paulo    # Ajuste seu fuso horário
