name: Metrics

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Compact display
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
